services:
  - type: web
    name: echt-hr-api
    runtime: docker
    plan: free
    port: 4000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: echt-hr-db
          property: connectionString
      - key: AZURE_AD_TENANT_ID
        sync: false
      - key: AZURE_AD_CLIENT_ID
        sync: false
      - key: AZURE_AD_CLIENT_SECRET
        sync: false
      - key: AZURE_AD_ISSUER
        sync: false
      - key: AZURE_AD_AUDIENCE
        sync: false
      - key: FRONTEND_URL
        value: https://hr-management-system-steel-delta.vercel.app

databases:
  - name: echt-hr-db
    plan: free
    databaseName: echt_hr
    user: echt
